[build]
  command = "yarn build"
  publish = "dist"
[build.environment]
  YARN_VERSION = "1.9.4"

[context.deploy-preview]
  command = "yarn build-preview"

- label: "Tags"
  name: "tags"
  widget: "list"
  default: ["news"]